# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfaae9f2c0b708b160d04ccbc606c248787cbadec19743d435836c25bfa4c33e20550e124ceb363125793dae46ada07c51d7be9d46ab01fce44c7034596b1309

test:
  secret_key_base: 63ff7efb23fba79bfd50f25ffa829790eda0373cf2c9b03c8391d4e8a1eea3f281cc22963783f150af2a665ff82203abfef15decda09d728a3900adcf2451194

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
